### PR TITLE
Properly support keyframes and animation

### PR DESCRIPTION
**Pull request by miracle2k**
There are multiple problems with this currently.
- animation is not rewritten. This is added in e2b11d27 here.
- keyframe rewrite fails when already prefixed in the input (the rule is removed entirely).
- keyframe rewrite doesn't work with percentage values, only "from" and "to". This last one is hard to solve, because cssutils refuses to parse it. cssutils is under active development. I would think that the best way to solve this would be to properly support @keyframes there.

### CODE REVIEW

**Comment by miracle2k** [comment]
I added a ticket @ cssutils:

https://bitbucket.org/cthedot/cssutils/issue/17/support-keyframes

I also notice that UnknownCSSRule has the tokens in a .seq property, but I doubt that would be useful.

**Comment by miracle2k** [comment]
I can across another bug:

```
 @keyframes round /* blabla */ {   }
```

And also one that's messy to fix. I really see the solution here in making cssutils understand the keyframes rule.

**Comment by stevenle** [comment]
Just noticed this pull request is ~3 months old. Are there plans to incorporate this into the master branch?

**Comment by valpackett** [comment]
Um, why should I merge failing tests? Write the code that does the job.

**Comment by stevenle** [comment]
@miracle2k: Are you still working on fixing the tests?

**Comment by miracle2k** [comment]
@stevenle  My intention was to add support for the keyframe rule to cssutils (ticket here: https://bitbucket.org/cthedot/cssutils/issue/17/support-keyframes), but due to the overly complex way the cssutils parser works, I basically gave up for now.

I also shortly considered porting the whole thing to use tinycss (https://github.com/SimonSapin/tinycss/).

**Pull request closed without merging**
